---
title: "Water for Good"
subtitle: "Report"
format: html
editor: visual
execute:
  echo: false 
  warning: false
  message: false
---

```{r}
#| label: Read libraries

library(readr)
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(tidymodels)
library(skimr)

baseline <- read.csv("data/CO2_HH_Baseline.csv")
project <- read.csv("data/project.csv")
slice(baseline)
```

```{r}

baseline |>
  filter(!is.na(X.How.many.trips.did.that.person.make.in.the.last.week.)) |>
  filter(!is.na(X.Number.of.minutes.to.collect.water.))
```

```{r}

baseline |>
  ggplot(aes(x = X.Number.of.minutes.to.collect.water.)) + 
  geom_histogram()
```

```{r}

project |>
  ggplot(aes(x = Record.the.number.of.minutes.it.takes.to.walk.from.the.house.to.the.water.point..collect.the.water..including.waiting.in.line..and.return.home..)) +
  geom_histogram()
```

```{r}
baseline |>
  skim(X.Number.of.minutes.to.collect.water.) |>
  select(-skim_type, -skim_variable, -complete_rate, -numeric.hist) |>
  print(width = Inf)
```

```{r}
project |>
  skim(Record.the.number.of.minutes.it.takes.to.walk.from.the.house.to.the.water.point..collect.the.water..including.waiting.in.line..and.return.home..) |>
  select(-skim_type, -skim_variable, -complete_rate, -numeric.hist) |>
  print(width = Inf)
```

Both datasets are clearly right skewed therefore using the median amount of time for water collection drastically decreased from the baseline to the recent project survey. The median amount of time for water collection decreased from about 60 to 15 minutes. With the ranges also being drastically smaller for the minutes for the post survey.
